services:

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1048
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/react-tutorial.pfx
    container_name: react-tutorial-api
    image: react-tutorial-api
    build:
      context: react-tutorial-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ~/.aspnet/https:/https:ro

  frontend:
    build:
      context: react
      dockerfile: Dockerfile
    image: react-tutorial-frontend
    container_name: "react-tutorial-frontend"
    ports:
      - "5173:5173"
    depends_on:
      - api