// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using custom_randomizer_api.Models;

#nullable disable

namespace customrandomizerapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250624161255_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Randomizer.Randomizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Instant>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Randomizers");
                });

            modelBuilder.Entity("custom_randomizer_api.Models.Trait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Instant>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Instant?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RandomizerId")
                        .HasColumnType("integer");

                    b.Property<int>("TraitType")
                        .HasColumnType("integer");

                    b.Property<Instant>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("RandomizerId");

                    b.ToTable("Traits");
                });

            modelBuilder.Entity("custom_randomizer_api.Models.TraitOptions.TraitOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<int>("TraitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TraitId");

                    b.ToTable("TraitOptions");

                    b.HasDiscriminator().HasValue("TraitOption");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("custom_randomizer_api.Models.TraitOptions.BasicTraitOption", b =>
                {
                    b.HasBaseType("custom_randomizer_api.Models.TraitOptions.TraitOption");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("custom_randomizer_api.Models.TraitOptions.ColorTraitOption", b =>
                {
                    b.HasBaseType("custom_randomizer_api.Models.TraitOptions.TraitOption");

                    b.HasDiscriminator().HasValue("Color");
                });

            modelBuilder.Entity("custom_randomizer_api.Models.TraitOptions.NumberTraitOption", b =>
                {
                    b.HasBaseType("custom_randomizer_api.Models.TraitOptions.TraitOption");

                    b.Property<int>("MaxNum")
                        .HasColumnType("integer");

                    b.Property<int>("MinNum")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Number");
                });

            modelBuilder.Entity("custom_randomizer_api.Models.Trait", b =>
                {
                    b.HasOne("Models.Randomizer.Randomizer", "Randomizer")
                        .WithMany("Traits")
                        .HasForeignKey("RandomizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Randomizer");
                });

            modelBuilder.Entity("custom_randomizer_api.Models.TraitOptions.TraitOption", b =>
                {
                    b.HasOne("custom_randomizer_api.Models.Trait", "Trait")
                        .WithMany("TraitOptions")
                        .HasForeignKey("TraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trait");
                });

            modelBuilder.Entity("Models.Randomizer.Randomizer", b =>
                {
                    b.Navigation("Traits");
                });

            modelBuilder.Entity("custom_randomizer_api.Models.Trait", b =>
                {
                    b.Navigation("TraitOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
