
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Development
WORKDIR /src
EXPOSE 8080
EXPOSE 8081
COPY ["custom-randomizer-api.csproj", "."]
RUN dotnet restore "./custom-randomizer-api.csproj"
COPY . .
WORKDIR "/src/."
CMD ["dotnet", "watch", "run", "--project" , "custom-randomizer-api.csproj", "--urls", "http://*:8080;https://*:8081"]
